
spring:
  datasource:
    url: jdbc:mysql://localhost:443/spring?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
server:
  port: 8080
